" Generated by vim-plug
" Fri  1 Jul 16:40:40 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ag.vim'].commit = '4a0dd6e190f446e5a016b44fdaa2feafc582918e'
silent! let g:plugs['fzf'].commit = '885cd8ff04e73d61279f0ac58011f74613e809dd'
silent! let g:plugs['fzf.vim'].commit = 'c311c0a95fc2529c26ab36a8f530e9dd4426304c'
silent! let g:plugs['lightline.vim'].commit = 'b02ef0d9f253dfc1cbb3f340b74998d7a4db0bf6'
silent! let g:plugs['matchit.zip'].commit = 'ced6c409c9beeb0b4142d21906606bd194411d1d'
silent! let g:plugs['vim-abolish'].commit = '3f0c8faadf0c5b68bcf40785c1c42e3731bfa522'
silent! let g:plugs['vim-bundler'].commit = '43da96e6ea726c1a91b8b7ceea1d6019df4231d7'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-dispatch'].commit = '00e77d90452e3c710014b26dc61ea919bc895e92'
silent! let g:plugs['vim-endwise'].commit = '4ed852d137853a0c242846fd0a61a241b4c7b467'
silent! let g:plugs['vim-eunuch'].commit = '39e0232f490322c5a2d9e24275872f28da496a93'
silent! let g:plugs['vim-fugitive'].commit = 'f809dde0e719f89a6fb5cb80f3be65f5cbc1d1fe'
silent! let g:plugs['vim-rails'].commit = '6bc0c7826d68f8c44c8347a3012aa79ade4f0a22'
silent! let g:plugs['vim-rake'].commit = '6b6ac578c27f0625f23164a8f9dc104578d32859'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rhubarb'].commit = 'c815057f8e8ace962a1f653b6ab5c35678662a86'
silent! let g:plugs['vim-rspec'].commit = '52a72592b6128f4ef1557bc6e2e3eb014d8b2d38'
silent! let g:plugs['vim-surround'].commit = 'bf3480dc9ae7bea34c78fbba4c65b4548b5b1fea'
silent! let g:plugs['vim-unimpaired'].commit = 'efdc6475f7ea789346716dabf9900ac04ee8604a'

PlugUpdate!

